#!/usr/bin/env sh
VOLUME=${VOLUME:-/docker}
ALLOW=${ALLOW:-192.168.0.0/16 172.16.0.0/12}
OWNER=${OWNER:-nobody}
GROUP=${GROUP:-nogroup}
OWNERID=${OWNERID:-1000}
GROUPID=${GROUPID:-1000}

mkdir -p $VOLUME

id -u $GROUP &>/dev/null || (addgroup -g $GROUPID $GROUP && echo "created group $GROUP with id $GROUPID")
# option -N does not seem to be available,
# option -D sets no pw for user
id -u $OWNER &>/dev/null || (adduser  -D -G $GROUP -u $OWNERID $OWNER -h $VOLUME && echo "created user $OWNER with id $OWNERID")

chown "${OWNER}:${GROUP}" "${VOLUME}"

if [ -f '/var/run/rsyncd.pid' ]; then
  PID=`cat /var/run/rsyncd.pid`
  echo "pidfile exsits with pid $PID, killing and removing it - restarting further on"
  killall $PID > /dev/null 2>&1  
  rm /var/run/rsyncd.pid
fi

# see https://wiki.alpinelinux.org/wiki/Setting_the_timezone
if [ -n ${TZ} ] && [ -f /usr/share/zoneinfo/${TZ} ]; then
    ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime
    echo ${TZ} > /etc/timezone
fi

# updated condition if rsyncd.conf exist
[ -f /etc/rsyncd.conf ] || cat <<EOF > /etc/rsyncd.conf
pid file = /var/run/rsyncd.pid
uid = ${OWNER}
gid = ${GROUP}
use chroot = no
log file = /dev/stdout
reverse lookup = no
[volume]
    hosts deny = *
    hosts allow = ${ALLOW}
    read only = false
    path = ${VOLUME}
    comment = docker volume
EOF

exec /usr/bin/rsync --no-detach --daemon --config="/etc/rsyncd.conf" "$@"
