#!/usr/bin/env sh
VOLUME=${VOLUME:-/docker}
ALLOW=${ALLOW:-192.168.0.0/16 172.16.0.0/12}
OWNER=${OWNER:-nobody}
GROUP=${GROUP:-nogroup}
OWNERID=${OWNERID:-1000}
GROUPID=${GROUPID:-1000}

mkdir -p $VOLUME

id -u $GROUP &>/dev/null || (addgroup -g $GROUPID $GROUP && echo "created group $GROUP with id $GROUPID")
# option -N does not seem to be available,
# option -D sets no pw for user
id -u $OWNER &>/dev/null || (adduser  -D -G $GROUP -u $OWNERID $OWNER -h $VOLUME && echo "created user $OWNER with id $OWNERID")

chown "${OWNER}:${GROUP}" "${VOLUME}"

# updated condition if rsyncd.conf exist
[ -f /etc/rsyncd.conf ] || cat <<EOF > /etc/rsyncd.conf
pid file = /var/run/rsyncd.pid
uid = ${OWNER}
gid = ${GROUP}
use chroot = no
log file = /dev/stdout
reverse lookup = no
[volume]
    hosts deny = *
    hosts allow = ${ALLOW}
    read only = false
    path = ${VOLUME}
    comment = docker volume
EOF

exec /usr/bin/rsync --no-detach --daemon --config="/etc/rsyncd.conf" "$@"
